[package]
name = "vfsstat_rs"
version = "0.1.0"
edition = "2021"
authors = ["Manos Pitsidianakis <manos@pitsidianak.is>"]
publish = false
rust-version = "1.71.1"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
log = { version = "0.4" }
